version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: "DiscountCodes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
  client:
    build:
      context: "./UI"
    ports:
      - "3000:80"
      - "3000"
  server:
    build:
      context: .
    depends_on:
    - db
    environment:
    - ASPNETCORE_URLS=http://+:11110
    - ASPNETCORE_HTTPS_PORT=https://+:11111
    - ASPNETCORE_ENVIRONMENT=Development
    # - ASPNETCORE_Kestrel__Certificates__Default__Password=12345678
    # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "11110:11110"
      - "11111:11111"
      - "11111"

# Names our volume
volumes:
  my-db: