name: Main CI /CD pipeline

on:
    workflow_dispatch:
    push:
        branches: [ main ]

jobs:

  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Run test
        id: run-tests
        run: dotnet test *.sln
