name: Main CI /CD pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Run test
        id: run-tests
        run: dotnet test *.sln

  run-sonar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Analyze with SonarCloud
        uses: highbyte/sonarscan-dotnet@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        with:
          sonarOrganization: valentk777
          sonarProjectKey: valentk777_Task-DiscountCodes
          sonarProjectName: Task-DiscountCodes
          dotnetTestArguments: --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"

      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        timeout-minutes: 1 # Force to fail step after specific time.
        with:
          scanMetadataReportFile: .sonarqube/out/.sonar/report-task.txt
